name: Slack notification on issue with bug label is created
on: push
jobs:
  Send-Notification-To-Slack:
    runs-on: ubuntu-latest
    steps:
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
