name: Slack notification on issue with bug label is created
on:
  issues:
    types: [opened]
jobs:
  Get-Information-About-Issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{github.event.issue.labels[0].name}} Label and Sender name is ${{github.event.sender.login}} and ${{github.event.sender.node_id}} '
