name: Slack notification on issue with bug label is created
on:
  issues:
    types: [opened]
jobs:
  Send-Notification-To-Slack:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::info message=hello'
