name: Slack notification on issue with bug label is created
on:
  issues:
    types: [opened]
jobs:
  Get-Information-About-Issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{github.event.label}} Label and ${{github.event.issue.labels}} Lebels'
