name: Slack notification on issue with bug label is created
on:
  issues:
    types: [opened]
jobs:
  issue_openend:
    name: Issue Opened
    if : ${{contains(github.event.issue.labels.*.name, 'bug')}}
    runs-on: ubuntu-latest
    steps:
      - name: Get details of issue
        id: issue-details
        run : |
          echo '::set-output name=issue_raised_by::${{github.event.sender.login}}'
          echo '::set-output name=issue_title::${{github.event.issue.title}}'
          echo '::set-output name=repo_url::${{github.event.repository.html_url}}'
          echo '::set-output name=issue_url::${{github.event.issue.html_url}}'
      - name: Send notification to slack   
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02JGCJ7RD3'
          payload: "{\"text\":\":ladybug:*${{ steps.issue-details.outputs.issue_title }}* has been raised by *${{ steps.issue-details.outputs.issue_raised_by }}*\n*• Issue Url*- ${{ steps.issue-details.outputs.issue_url }}\n*• Repo Url*- ${{ steps.issue-details.outputs.repo_url }}\"}"  
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLAC_BOT_TOKEN }}
